UIROLES-45: add ability to delete role in the role details pane
folio-org/ui-authorization-roles pull request #28
Opened 2024-02-29 10:01 UTC by aidynoJ

2024-03-05 12:18 UTC, zburke requested changes
[UIROLES-45](https://folio-org.atlassian.net/browse/UIROLES-45) includes two parts:
* [x] wire up the delete API call
* [x] show a confirmation modal

Ryan's comment to add minimal error handling is worthwhile as well.

2024-03-06 14:31 UTC, ryandberger approved these changes

2024-03-07 18:35 UTC, zburke approved these changes
LGTM, but please clean up the i18n in RoleDetails. It's not good to break up translations across multiple messages because translators may not receive the appropriate context to handle things correctly.

2024-03-07 18:35 UTC, zburke commented on src/settings/components/RoleDetails/RoleDetails.js
> +          {' '} <b><FormattedMessage id="ui-authorization-roles.crud.deleted" /></b> </>}
Please embed the styling in the translation to avoid breaking a single phrase across multiple messages.

2024-03-08 10:15 UTC, merged