UIROLES-75: show only capabilities/capabilitySets for enabled (versions of) applications,  use chunked requests on capabilities, capability-sets
folio-org/ui-authorization-roles pull request #64
Opened 2024-05-28 12:29 UTC by aidynoJ

[Refs UIROLES-75., ](https://folio-org.atlassian.net/browse/UIROLES-75) - Only display capabilities/capabilitySets for enabled (versions of) applications. Gracefully handle the case where there are so many applications that the query grows too large.

2024-05-29 03:34 UTC, zburke reviewed
From the angle of correctness, I think this PR LGTM. I expected the query changes and the introduction of useChunkedCQLFetch, but there's more going on here and it's difficult to follow since the original code isn't well-commented. Tests and documentation are a little too light to approve as-is.

2024-05-30 11:11 UTC, aidynoJ commented on src/settings/components/CreateEditRole/CreateEditRoleForm.js
> +    <Layer isOpen inRootSet contentLabel={<FormattedMessage id={title} />}>
Yes, sorry. Accidentally reverted when updated the branch

2024-05-30 11:13 UTC, aidynoJ commented on src/settings/components/CreateEditRole/CreateRole.test.js
> -
Fixed

2024-05-30 11:15 UTC, aidynoJ commented on src/hooks/useApplicationCapabilities.js
> -  */
Yes, I agree. I didn't notice how it has been grown. I split it into 2 separate hooks for capabilities, capability-sets. And provided descriptive JS Doc

2024-05-30 11:16 UTC, aidynoJ commented on src/hooks/useCapabilities.js
> +
Got it. The issue with the length of the query, I suggest) Thank you

2024-05-30 11:17 UTC, aidynoJ commented on src/settings/components/CreateEditRole/CreateRole.js
> +  const isCapabilitySelected = id => !!selectedCapabilitiesMap[id] || isCapabilityDisabled(id);
Added explanation

2024-06-03 20:23 UTC, zburke requested changes
Unfortunately, the role-create and role-edit pages no longer populate the "Capability sets" or "Capabilities" accordions for me. I can see the queries in the network inspector, but the UI does not show any data.

Compared to the previous commit, the documentation changes are perfect and helpful and I have resolved all those comments. But now we need to figure out what else changed in the refactor.

2024-06-04 03:45 UTC, aidynoJ commented
> Unfortunately, the role-create and role-edit pages no longer populate the "Capability sets" or "Capabilities" accordions for me. I can see the queries in the network inspector, but the UI does not show any data.
> 
> 
> 
> Compared to the previous commit, the documentation changes are perfect and helpful and I have resolved all those comments. But now we need to figure out what else changed in the refactor. 

Interesting, I'll check that out. Thank you

2024-06-06 12:29 UTC, zburke approved these changes
Ohhhhhhh, I understand how this works now, and I apologize for blocking this when it has worked correctly for so long :( The UI here is not intuitive, but that's not your fault. When creating a new Role, in order to show available Capability Sets it is necessary to first select Applications from Capability accordion. This is not intuitive, but it does work.

Since selected Applications determine the available Capability sets and Capabilities, Applications need to be displayed in a hierarchy *above* both, like so:
```
> Application list
  * [ ] App A
  * [*] App B
  > Capability sets
    * [ ] Set A
    * [ ] Set B
  > Capabilities
    * [ ] Capability A
    * [ ] Capability B
    * [ ] Capability C

```

2024-06-07 11:29 UTC, merged